// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: dataclean.proto

package dataclean_client

import (
	"context"

	"sea-try-go/service/dataclean/rpc/pb/dataclean"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CleanArticleRequest  = dataclean.CleanArticleRequest
	CleanArticleResponse = dataclean.CleanArticleResponse

	Dataclean interface {
		CleanArticle(ctx context.Context, in *CleanArticleRequest, opts ...grpc.CallOption) (*CleanArticleResponse, error)
	}

	defaultDataclean struct {
		cli zrpc.Client
	}
)

func NewDataclean(cli zrpc.Client) Dataclean {
	return &defaultDataclean{
		cli: cli,
	}
}

func (m *defaultDataclean) CleanArticle(ctx context.Context, in *CleanArticleRequest, opts ...grpc.CallOption) (*CleanArticleResponse, error) {
	client := dataclean.NewDatacleanClient(m.cli.Conn())
	return client.CleanArticle(ctx, in, opts...)
}
