// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/favorite.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     uint64                 `protobuf:"varint,2,opt,name=Article_id,json=ArticleId,proto3" json:"Article_id,omitempty"`
	ActionType    uint32                 `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` //0是收藏1是取消收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionReq) Reset() {
	*x = FavoriteActionReq{}
	mi := &file_proto_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionReq) ProtoMessage() {}

func (x *FavoriteActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionReq.ProtoReflect.Descriptor instead.
func (*FavoriteActionReq) Descriptor() ([]byte, []int) {
	return file_proto_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteActionReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteActionReq) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *FavoriteActionReq) GetActionType() uint32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type FavoriteActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionResp) Reset() {
	*x = FavoriteActionResp{}
	mi := &file_proto_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionResp) ProtoMessage() {}

func (x *FavoriteActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionResp.ProtoReflect.Descriptor instead.
func (*FavoriteActionResp) Descriptor() ([]byte, []int) {
	return file_proto_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteActionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FavoriteListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListReq) Reset() {
	*x = FavoriteListReq{}
	mi := &file_proto_favorite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListReq) ProtoMessage() {}

func (x *FavoriteListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_favorite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListReq.ProtoReflect.Descriptor instead.
func (*FavoriteListReq) Descriptor() ([]byte, []int) {
	return file_proto_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *FavoriteListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FavoriteListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FavoriteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint64                 `protobuf:"varint,1,opt,name=Article_id,json=ArticleId,proto3" json:"Article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteItem) Reset() {
	*x = FavoriteItem{}
	mi := &file_proto_favorite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteItem) ProtoMessage() {}

func (x *FavoriteItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_favorite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteItem.ProtoReflect.Descriptor instead.
func (*FavoriteItem) Descriptor() ([]byte, []int) {
	return file_proto_favorite_proto_rawDescGZIP(), []int{3}
}

func (x *FavoriteItem) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type FavoriteListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FavoriteItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListResp) Reset() {
	*x = FavoriteListResp{}
	mi := &file_proto_favorite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListResp) ProtoMessage() {}

func (x *FavoriteListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_favorite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListResp.ProtoReflect.Descriptor instead.
func (*FavoriteListResp) Descriptor() ([]byte, []int) {
	return file_proto_favorite_proto_rawDescGZIP(), []int{4}
}

func (x *FavoriteListResp) GetList() []*FavoriteItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *FavoriteListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_favorite_proto protoreflect.FileDescriptor

const file_proto_favorite_proto_rawDesc = "" +
	"\n" +
	"\x14proto/favorite.proto\x12\bfavorite\"l\n" +
	"\x11FavoriteActionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"Article_id\x18\x02 \x01(\x04R\tArticleId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\rR\n" +
	"actionType\".\n" +
	"\x12FavoriteActionResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x0fFavoriteListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"-\n" +
	"\fFavoriteItem\x12\x1d\n" +
	"\n" +
	"Article_id\x18\x01 \x01(\x04R\tArticleId\"T\n" +
	"\x10FavoriteListResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.favorite.FavoriteItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xa8\x01\n" +
	"\x0fFavoriteService\x12K\n" +
	"\x0eFavoriteAction\x12\x1b.favorite.FavoriteActionReq\x1a\x1c.favorite.FavoriteActionResp\x12H\n" +
	"\x0fGetFavoriteList\x12\x19.favorite.FavoriteListReq\x1a\x1a.favorite.FavoriteListRespB\x03Z\x01.b\x06proto3"

var (
	file_proto_favorite_proto_rawDescOnce sync.Once
	file_proto_favorite_proto_rawDescData []byte
)

func file_proto_favorite_proto_rawDescGZIP() []byte {
	file_proto_favorite_proto_rawDescOnce.Do(func() {
		file_proto_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_favorite_proto_rawDesc), len(file_proto_favorite_proto_rawDesc)))
	})
	return file_proto_favorite_proto_rawDescData
}

var file_proto_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_favorite_proto_goTypes = []any{
	(*FavoriteActionReq)(nil),  // 0: favorite.FavoriteActionReq
	(*FavoriteActionResp)(nil), // 1: favorite.FavoriteActionResp
	(*FavoriteListReq)(nil),    // 2: favorite.FavoriteListReq
	(*FavoriteItem)(nil),       // 3: favorite.FavoriteItem
	(*FavoriteListResp)(nil),   // 4: favorite.FavoriteListResp
}
var file_proto_favorite_proto_depIdxs = []int32{
	3, // 0: favorite.FavoriteListResp.list:type_name -> favorite.FavoriteItem
	0, // 1: favorite.FavoriteService.FavoriteAction:input_type -> favorite.FavoriteActionReq
	2, // 2: favorite.FavoriteService.GetFavoriteList:input_type -> favorite.FavoriteListReq
	1, // 3: favorite.FavoriteService.FavoriteAction:output_type -> favorite.FavoriteActionResp
	4, // 4: favorite.FavoriteService.GetFavoriteList:output_type -> favorite.FavoriteListResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_favorite_proto_init() }
func file_proto_favorite_proto_init() {
	if File_proto_favorite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_favorite_proto_rawDesc), len(file_proto_favorite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_favorite_proto_goTypes,
		DependencyIndexes: file_proto_favorite_proto_depIdxs,
		MessageInfos:      file_proto_favorite_proto_msgTypes,
	}.Build()
	File_proto_favorite_proto = out.File
	file_proto_favorite_proto_goTypes = nil
	file_proto_favorite_proto_depIdxs = nil
}
