// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: favorite.proto

package server

import (
	"context"

	"sea-try-go/service/favorite/rpc/internal/logic"
	"sea-try-go/service/favorite/rpc/internal/svc"
	"sea-try-go/service/favorite/rpc/pb"
)

type FavoriteServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedFavoriteServiceServer
}

func NewFavoriteServiceServer(svcCtx *svc.ServiceContext) *FavoriteServiceServer {
	return &FavoriteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServiceServer) FavoriteAction(ctx context.Context, in *__.FavoriteActionReq) (*__.FavoriteActionResp, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *FavoriteServiceServer) GetFavoriteList(ctx context.Context, in *__.FavoriteListReq) (*__.FavoriteListResp, error) {
	l := logic.NewGetFavoriteListLogic(ctx, s.svcCtx)
	return l.GetFavoriteList(in)
}
