// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: proto/dataclean.proto

package dataclean

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dataclean_CleanArticle_FullMethodName = "/dataclean.Dataclean/CleanArticle"
)

// DatacleanClient is the client API for Dataclean service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatacleanClient interface {
	CleanArticle(ctx context.Context, in *CleanArticleRequest, opts ...grpc.CallOption) (*CleanArticleResponse, error)
}

type datacleanClient struct {
	cc grpc.ClientConnInterface
}

func NewDatacleanClient(cc grpc.ClientConnInterface) DatacleanClient {
	return &datacleanClient{cc}
}

func (c *datacleanClient) CleanArticle(ctx context.Context, in *CleanArticleRequest, opts ...grpc.CallOption) (*CleanArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanArticleResponse)
	err := c.cc.Invoke(ctx, Dataclean_CleanArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatacleanServer is the server API for Dataclean service.
// All implementations must embed UnimplementedDatacleanServer
// for forward compatibility.
type DatacleanServer interface {
	CleanArticle(context.Context, *CleanArticleRequest) (*CleanArticleResponse, error)
	mustEmbedUnimplementedDatacleanServer()
}

// UnimplementedDatacleanServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatacleanServer struct{}

func (UnimplementedDatacleanServer) CleanArticle(context.Context, *CleanArticleRequest) (*CleanArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanArticle not implemented")
}
func (UnimplementedDatacleanServer) mustEmbedUnimplementedDatacleanServer() {}
func (UnimplementedDatacleanServer) testEmbeddedByValue()                   {}

// UnsafeDatacleanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatacleanServer will
// result in compilation errors.
type UnsafeDatacleanServer interface {
	mustEmbedUnimplementedDatacleanServer()
}

func RegisterDatacleanServer(s grpc.ServiceRegistrar, srv DatacleanServer) {
	// If the following call pancis, it indicates UnimplementedDatacleanServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dataclean_ServiceDesc, srv)
}

func _Dataclean_CleanArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatacleanServer).CleanArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dataclean_CleanArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatacleanServer).CleanArticle(ctx, req.(*CleanArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dataclean_ServiceDesc is the grpc.ServiceDesc for Dataclean service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dataclean_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataclean.Dataclean",
	HandlerType: (*DatacleanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CleanArticle",
			Handler:    _Dataclean_CleanArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dataclean.proto",
}
