// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: proto/dataclean.proto

package dataclean

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CleanArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArticleId       string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`                     // 文章ID
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                              // 标题
	Brief           *string                `protobuf:"bytes,3,opt,name=brief,proto3,oneof" json:"brief,omitempty"`                                        // 摘要（可选，自动截取正文前150字）
	MarkdownContent string                 `protobuf:"bytes,4,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"`   // 轻量 Markdown 正文
	CoverImageUrl   *string                `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"` // 封面图URL（可选）
	ManualTypeTag   string                 `protobuf:"bytes,6,opt,name=manual_type_tag,json=manualTypeTag,proto3" json:"manual_type_tag,omitempty"`       // 一级标签
	SecondaryTags   []string               `protobuf:"bytes,7,rep,name=secondary_tags,json=secondaryTags,proto3" json:"secondary_tags,omitempty"`         // 二级标签
	AuthorId        string                 `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                        // 作者ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CleanArticleRequest) Reset() {
	*x = CleanArticleRequest{}
	mi := &file_proto_dataclean_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanArticleRequest) ProtoMessage() {}

func (x *CleanArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataclean_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanArticleRequest.ProtoReflect.Descriptor instead.
func (*CleanArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataclean_proto_rawDescGZIP(), []int{0}
}

func (x *CleanArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *CleanArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CleanArticleRequest) GetBrief() string {
	if x != nil && x.Brief != nil {
		return *x.Brief
	}
	return ""
}

func (x *CleanArticleRequest) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *CleanArticleRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *CleanArticleRequest) GetManualTypeTag() string {
	if x != nil {
		return x.ManualTypeTag
	}
	return ""
}

func (x *CleanArticleRequest) GetSecondaryTags() []string {
	if x != nil {
		return x.SecondaryTags
	}
	return nil
}

func (x *CleanArticleRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CleanArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSafe        bool                   `protobuf:"varint,1,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanArticleResponse) Reset() {
	*x = CleanArticleResponse{}
	mi := &file_proto_dataclean_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanArticleResponse) ProtoMessage() {}

func (x *CleanArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataclean_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanArticleResponse.ProtoReflect.Descriptor instead.
func (*CleanArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataclean_proto_rawDescGZIP(), []int{1}
}

func (x *CleanArticleResponse) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *CleanArticleResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_dataclean_proto protoreflect.FileDescriptor

const file_proto_dataclean_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dataclean.proto\x12\tdataclean\"\xc7\x02\n" +
	"\x13CleanArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\x05brief\x18\x03 \x01(\tH\x00R\x05brief\x88\x01\x01\x12)\n" +
	"\x10markdown_content\x18\x04 \x01(\tR\x0fmarkdownContent\x12+\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tH\x01R\rcoverImageUrl\x88\x01\x01\x12&\n" +
	"\x0fmanual_type_tag\x18\x06 \x01(\tR\rmanualTypeTag\x12%\n" +
	"\x0esecondary_tags\x18\a \x03(\tR\rsecondaryTags\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\tR\bauthorIdB\b\n" +
	"\x06_briefB\x12\n" +
	"\x10_cover_image_url\"G\n" +
	"\x14CleanArticleResponse\x12\x17\n" +
	"\ais_safe\x18\x01 \x01(\bR\x06isSafe\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\\\n" +
	"\tDataclean\x12O\n" +
	"\fCleanArticle\x12\x1e.dataclean.CleanArticleRequest\x1a\x1f.dataclean.CleanArticleResponseB\rZ\v./datacleanb\x06proto3"

var (
	file_proto_dataclean_proto_rawDescOnce sync.Once
	file_proto_dataclean_proto_rawDescData []byte
)

func file_proto_dataclean_proto_rawDescGZIP() []byte {
	file_proto_dataclean_proto_rawDescOnce.Do(func() {
		file_proto_dataclean_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dataclean_proto_rawDesc), len(file_proto_dataclean_proto_rawDesc)))
	})
	return file_proto_dataclean_proto_rawDescData
}

var file_proto_dataclean_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dataclean_proto_goTypes = []any{
	(*CleanArticleRequest)(nil),  // 0: dataclean.CleanArticleRequest
	(*CleanArticleResponse)(nil), // 1: dataclean.CleanArticleResponse
}
var file_proto_dataclean_proto_depIdxs = []int32{
	0, // 0: dataclean.Dataclean.CleanArticle:input_type -> dataclean.CleanArticleRequest
	1, // 1: dataclean.Dataclean.CleanArticle:output_type -> dataclean.CleanArticleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dataclean_proto_init() }
func file_proto_dataclean_proto_init() {
	if File_proto_dataclean_proto != nil {
		return
	}
	file_proto_dataclean_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dataclean_proto_rawDesc), len(file_proto_dataclean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dataclean_proto_goTypes,
		DependencyIndexes: file_proto_dataclean_proto_depIdxs,
		MessageInfos:      file_proto_dataclean_proto_msgTypes,
	}.Build()
	File_proto_dataclean_proto = out.File
	file_proto_dataclean_proto_goTypes = nil
	file_proto_dataclean_proto_depIdxs = nil
}
