// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: favorite.proto

package favoriteservice

import (
	"context"

	"sea-try-go/service/favorite/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteActionReq  = __.FavoriteActionReq
	FavoriteActionResp = __.FavoriteActionResp
	FavoriteItem       = __.FavoriteItem
	FavoriteListReq    = __.FavoriteListReq
	FavoriteListResp   = __.FavoriteListResp

	FavoriteService interface {
		FavoriteAction(ctx context.Context, in *FavoriteActionReq, opts ...grpc.CallOption) (*FavoriteActionResp, error)
		GetFavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
	}

	defaultFavoriteService struct {
		cli zrpc.Client
	}
)

func NewFavoriteService(cli zrpc.Client) FavoriteService {
	return &defaultFavoriteService{
		cli: cli,
	}
}

func (m *defaultFavoriteService) FavoriteAction(ctx context.Context, in *FavoriteActionReq, opts ...grpc.CallOption) (*FavoriteActionResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

func (m *defaultFavoriteService) GetFavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	client := __.NewFavoriteServiceClient(m.cli.Conn())
	return client.GetFavoriteList(ctx, in, opts...)
}
