// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: article.proto

package server

import (
	"context"

	"sea-try-go/service/article/rpc/internal/logic"
	"sea-try-go/service/article/rpc/internal/svc"
	"sea-try-go/service/article/rpc/pb"
)

type ArticleServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedArticleServiceServer
}

func NewArticleServiceServer(svcCtx *svc.ServiceContext) *ArticleServiceServer {
	return &ArticleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServiceServer) GetArticle(ctx context.Context, in *__.GetArticleReq) (*__.GetArticleResp, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

func (s *ArticleServiceServer) CreateArticle(ctx context.Context, in *__.CreateArticleReq) (*__.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *ArticleServiceServer) UpdateArticle(ctx context.Context, in *__.UpdateArticleReq) (*__.UpdateArticleResp, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *ArticleServiceServer) DeleteArticle(ctx context.Context, in *__.DeleteArticleReq) (*__.DeleteArticleResp, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}
