// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package pointsservice

import (
	"context"

	"sea-try-go/service/points/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleExposureReq  = __.AddArticleExposureReq
	AddArticleExposureResp = __.AddArticleExposureResp
	Article                = __.Article
	Data                   = __.Data
	GetUserArticleReq      = __.GetUserArticleReq
	GetUserArticleResp     = __.GetUserArticleResp
	GetUserPointsReq       = __.GetUserPointsReq
	GetUserPointsResp      = __.GetUserPointsResp
	LoginPointsReq         = __.LoginPointsReq
	LoginPointsResp        = __.LoginPointsResp
	PointsInfo             = __.PointsInfo

	PointsService interface {
		LoginPoints(ctx context.Context, in *LoginPointsReq, opts ...grpc.CallOption) (*LoginPointsResp, error)
		GetUserPoints(ctx context.Context, in *GetUserPointsReq, opts ...grpc.CallOption) (*GetUserPointsResp, error)
		GetUserArticle(ctx context.Context, in *GetUserArticleReq, opts ...grpc.CallOption) (*GetUserArticleResp, error)
		AddArticleExposure(ctx context.Context, in *AddArticleExposureReq, opts ...grpc.CallOption) (*AddArticleExposureResp, error)
	}

	defaultPointsService struct {
		cli zrpc.Client
	}
)

func NewPointsService(cli zrpc.Client) PointsService {
	return &defaultPointsService{
		cli: cli,
	}
}

func (m *defaultPointsService) LoginPoints(ctx context.Context, in *LoginPointsReq, opts ...grpc.CallOption) (*LoginPointsResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.LoginPoints(ctx, in, opts...)
}

func (m *defaultPointsService) GetUserPoints(ctx context.Context, in *GetUserPointsReq, opts ...grpc.CallOption) (*GetUserPointsResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.GetUserPoints(ctx, in, opts...)
}

func (m *defaultPointsService) GetUserArticle(ctx context.Context, in *GetUserArticleReq, opts ...grpc.CallOption) (*GetUserArticleResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.GetUserArticle(ctx, in, opts...)
}

func (m *defaultPointsService) AddArticleExposure(ctx context.Context, in *AddArticleExposureReq, opts ...grpc.CallOption) (*AddArticleExposureResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.AddArticleExposure(ctx, in, opts...)
}
