// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: dataclean.proto

package server

import (
	"context"

	"sea-try-go/service/dataclean/rpc/internal/logic"
	"sea-try-go/service/dataclean/rpc/internal/svc"
	"sea-try-go/service/dataclean/rpc/pb/dataclean"
)

type DatacleanServer struct {
	svcCtx *svc.ServiceContext
	dataclean.UnimplementedDatacleanServer
}

func NewDatacleanServer(svcCtx *svc.ServiceContext) *DatacleanServer {
	return &DatacleanServer{
		svcCtx: svcCtx,
	}
}

func (s *DatacleanServer) CleanArticle(ctx context.Context, in *dataclean.CleanArticleRequest) (*dataclean.CleanArticleResponse, error) {
	l := logic.NewCleanArticleLogic(ctx, s.svcCtx)
	return l.CleanArticle(in)
}
